const carsData = [
  {
    id: 1,
    title: "Car 1",
    description: "Compact car",
    price: 10000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Toyota",
    model: "Corolla",
    year: 2020,
    color: "Red",
  },
  {
    id: 2,
    title: "Car 2",
    description: "Luxury SUV",
    price: 20000,
    fuelType: "Diesel",
    capacity: 7,
    brand: "BMW",
    model: "X5",
    year: 2021,
    color: "Black",
  },
  {
    id: 3,
    title: "Car 3",
    description: "Electric sedan",
    price: 30000,
    fuelType: "Electric",
    capacity: 5,
    brand: "Tesla",
    model: "Model 3",
    year: 2022,
    color: "White",
  },
  // ... add 27 more car objects
  {
    id: 4,
    title: "Car 4",
    description: "Sporty coupe",
    price: 25000,
    fuelType: "Petrol",
    capacity: 4,
    brand: "Audi",
    model: "A5",
    year: 2019,
    color: "Blue",
  },
  {
    id: 5,
    title: "Car 5",
    description: "Family minivan",
    price: 18000,
    fuelType: "Petrol",
    capacity: 7,
    brand: "Honda",
    model: "Odyssey",
    year: 2018,
    color: "Silver",
  },
  {
    id: 6,
    title: "Car 6",
    description: "Compact SUV",
    price: 15000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Hyundai",
    model: "Tucson",
    year: 2021,
    color: "Gray",
  },
  {
    id: 7,
    title: "Car 7",
    description: "Luxury sedan",
    price: 35000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: 2020,
    color: "Black",
  },
  {
    id: 8,
    title: "Car 8",
    description: "Electric hatchback",
    price: 22000,
    fuelType: "Electric",
    capacity: 5,
    brand: "Nissan",
    model: "Leaf",
    year: 2022,
    color: "Green",
  },
  {
    id: 9,
    title: "Car 9",
    description: "Off-road SUV",
    price: 27000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Jeep",
    model: "Wrangler",
    year: 2019,
    color: "Yellow",
  },
  {
    id: 10,
    title: "Car 10",
    description: "Luxury convertible",
    price: 40000,
    fuelType: "Petrol",
    capacity: 4,
    brand: "Porsche",
    model: "911",
    year: 2021,
    color: "Red",
  },
  {
    id: 11,
    title: "Car 11",
    description: "Compact sedan",
    price: 14000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Ford",
    model: "Focus",
    year: 2020,
    color: "Blue",
  },
  {
    id: 12,
    title: "Car 12",
    description: "Luxury SUV",
    price: 28000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Volvo",
    model: "XC90",
    year: 2019,
    color: "White",
  },
  {
    id: 13,
    title: "Car 13",
    description: "Electric sedan",
    price: 32000,
    fuelType: "Electric",
    capacity: 5,
    brand: "Tesla",
    model: "Model S",
    year: 2022,
    color: "Black",
  },
  {
    id: 14,
    title: "Car 14",
    description: "Sporty hatchback",
    price: 17000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Volkswagen",
    model: "Golf GTI",
    year: 2018,
    color: "Red",
  },
  {
    id: 15,
    title: "Car 15",
    description: "Family SUV",
    price: 19000,
    fuelType: "Diesel",
    capacity: 7,
    brand: "Chevrolet",
    model: "Tahoe",
    year: 2020,
    color: "Blue",
  },
  {
    id: 16,
    title: "Car 16",
    description: "Luxury sedan",
    price: 36000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Lexus",
    model: "ES",
    year: 2021,
    color: "Silver",
  },
  {
    id: 17,
    title: "Car 17",
    description: "Electric compact",
    price: 21000,
    fuelType: "Electric",
    capacity: 4,
    brand: "BMW",
    model: "i3",
    year: 2022,
    color: "Green",
  },
  {
    id: 18,
    title: "Car 18",
    description: "Off-road truck",
    price: 30000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Ford",
    model: "F-150",
    year: 2019,
    color: "Gray",
  },
  {
    id: 19,
    title: "Car 19",
    description: "Luxury coupe",
    price: 38000,
    fuelType: "Petrol",
    capacity: 4,
    brand: "Audi",
    model: "A7",
    year: 2021,
    color: "Black",
  },
  {
    id: 20,
    title: "Car 20",
    description: "Compact minivan",
    price: 16000,
    fuelType: "Petrol",
    capacity: 7,
    brand: "Kia",
    model: "Carnival",
    year: 2020,
    color: "Yellow",
  },
  {
    id: 21,
    title: "Car 21",
    description: "Electric SUV",
    price: 33000,
    fuelType: "Electric",
    capacity: 5,
    brand: "Jaguar",
    model: "I-PACE",
    year: 2022,
    color: "White",
  },
  {
    id: 22,
    title: "Car 22",
    description: "Luxury sedan",
    price: 37000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2019,
    color: "Red",
  },
  {
    id: 23,
    title: "Car 23",
    description: "Compact SUV",
    price: 18000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Mazda",
    model: "CX-5",
    year: 2020,
    color: "Blue",
  },
  {
    id: 24,
    title: "Car 24",
    description: "Luxury convertible",
    price: 39000,
    fuelType: "Petrol",
    capacity: 4,
    brand: "BMW",
    model: "Z4",
    year: 2021,
    color: "Black",
  },
  {
    id: 25,
    title: "Car 25",
    description: "Sporty coupe",
    price: 26000,
    fuelType: "Diesel",
    capacity: 4,
    brand: "Chevrolet",
    model: "Camaro",
    year: 2022,
    color: "Green",
  },
  {
    id: 26,
    title: "Car 26",
    description: "Electric sedan",
    price: 34000,
    fuelType: "Electric",
    capacity: 5,
    brand: "Audi",
    model: "e-tron",
    year: 2019,
    color: "Silver",
  },
  {
    id: 27,
    title: "Car 27",
    description: "Luxury SUV",
    price: 29000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Lexus",
    model: "RX",
    year: 2020,
    color: "Gray",
  },
  {
    id: 28,
    title: "Car 28",
    description: "Family sedan",
    price: 13000,
    fuelType: "Diesel",
    capacity: 5,
    brand: "Hyundai",
    model: "Elantra",
    year: 2018,
    color: "White",
  },
  {
    id: 29,
    title: "Car 29",
    description: "Compact hatchback",
    price: 15000,
    fuelType: "Petrol",
    capacity: 5,
    brand: "Ford",
    model: "Fiesta",
    year: 2020,
    color: "Blue",
  },
  {
    id: 30,
    title: "Car 30",
    description: "Electric compact",
    price: 20000,
    fuelType: "Electric",
    capacity: 4,
    brand: "Nissan",
    model: "Leaf",
    year: 2021,
    color: "Red",
  },
];

export default carsData;
